version: 2.1
orbs:
  docker: circleci/docker@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:17.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Docker
          command: docker --version
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: /home/circleci/project/test
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/test-docker .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/test-docker:latest
          working_directory: /home/circleci/project/test
workflows:
  build-and-deploy:
    jobs:
      - build
